

__color_darkgrey__ = "darkgrey"
__color_lightgrey__ = "lightgrey"


__app_name__ = "PDF Toolz"
__about_title__ = "PDF Toolz 0.1"
__about_message__ = "This is an open source PDF-tool.\n\nCreated by: Maysam Haidary \n\nThis PDF-tool is based on \n'Didier Stevens\'s' pdf-tools available on \nhttp://blog.didierstevens.com"
__created_by__ = "Maysam Haidary"
__data__ = "2018/10/06"
__app_width_height__ = "900x570"
__loaded_file_name__ = ""
__loaded_file_path__ = ""
__disarm_title__ = "PDF Disarmed"
__pdf_not_selected__ = "Please select a PDF file."

__pdf_parser_name__ = "./PDF-Tools/pdfparser/pdf-parser.py"
__pdf_id_name__ = "./PDF-Tools/pdfid/pdfid.py"
__make_pdf_embedded_name__ = "./PDF-Tools/makepdf/make-pdf-embedded.py"
__make_pdf_javascript_name__ = "./PDF-Tools/makepdf/make-pdf-javascript.py"

__file_prompt_title__ = "File Name"
__output_file_text__ = "Please type a file name for the outfile (without extension)"
__object_id_title__ = "Object ID"
__object_id_text__ = "Please type the Object ID (digits only)"
__generateembedded_text__ = "Please type the object ID that you want to generate a python program out of it."
__type_message_title__ = "Message"
__type_message_text = "Please type a message or text to add it to the output PDF file."
__type_message_error_title__ = "No message"
__type_message_error_text__ = "No message is provided or it is cancelled. This will create the PDF will default message."
__display_file_name__ = "Display file name"
__display_file_text__ = "Please type a file name to be used in embedded PDF or leave blank for default"
__javascript_file_add_error_title__ = "No file loaded"
__javascript_file_add_error_text__ = "No file provided to embed to the PDF file or cancelled. The program will use the default file."
__javascript_title__ = "Javascript Code"
__javascript_msg__ = "Please paste the javascript code here that you want to use or leave blank for default.\n\n     Format: \"\"\"app.alert({cMsg: 'Message', cTitle: 'Title', nIcon: 3});\"\"\"\n"
__no_javascript_title__ = "No Javascript Code"
__no_javascript_text__ = "No javascript code was provided or cancelled. The tool will generate the pdf with the default 'app.alert' code"
__javascript_file__ = "Please paste here the name of the javascript file or leave blank for default"
__no_javascript_file_title__ = "No javascript file"
__no_javascript_file_text__ = "No javascript file was provided or cancelled. The tool will generate the pdf with the default options"
__new_file_name_title__ = "New file name"
__new_file_name_text__ = "Enter a name for the PDF."
__no_new_file_name_title__ = "No file name"
__no_new_file_name_text__ = "No file name was provided or cancelled. The program will use the default file name."
__no_payload_file_selected_title__ = "No payload file provided"
__no_payload_file_selected_text__ = "You have not provided a payload file to add it to the embeded file."
__enter_embedding_file_path_title__ = "Enter file path"
__enter_embedding_file_path_text__ = "Please enter the path to the file which will be embeded to the PDF."
__directorypath_title__ = "Directory Path"
__directorypath_text__ = "Please type the path to directory that you want to scan all of its files.\nThis will replaced the loaded pdf file (if any)."
__directorypath_NO_title__ = "No directory path"
__directorypath_NO_text__ = "No direcotry path is provided or its cancelled. The old settings still remain active."
__noObjectId_title__ = "No Object ID"
__noObjectId_text__ = "Entering an object ID was cancelled or left blank. The PDF will be parsed with the default options."
__noObjectId_2_text__ = "The provided object ID is not a valid integer. The PDF will be parsed with the default options."
__noPythonObjectId_text__ = "Entering an object ID was cancelled or left blank. The program will pick the default object ID and generate a python code out of it."
__noPythonObjectId_text__ = "The provided object ID is not a valid integer. The program will pick the default object ID and generate a python code out of it."
__noOutPutName_title__ = "No Output name"
__noOutPutName_text__ = "No output name was provided. It will only display the output of the command."


# About Page info
__aboutPage_about_text__ = "The PDF-Tools is an open source tool. You can use this tool to analyse PDF files or create PDF files for your test envoirnment (with the principe of 'Use at your own risk').\n"
__aboutPage_PDFiD_title__ = "PDF iD"
__aboutPage_PDFiD_text__ = "The PDFiD tool will anaylyse the PDF or any file your provide it, but the real focus remains over PDF files. It will visualize the tag names that make a PDF file. It will also show any javascript code or file embedded in the PDF, any other file (including executables) and any code embedded to the file. Using this tool you can also disarm javascript of a PDF file.\n"
__aboutPage_PDFParser_title__ = "PDF Parser"
__aboutPage_PDFParser_text__ = "The PDF parser tool will parse each and every object of the PDF file. This tool will give you a good visual view of the objects that made the PDF file. You can use any object  inside the PDF file or the PDF file itself to create a python program.\n"
__aboutPage_PDFEmbedded_title__ = "Create PDF Embedded"
__aboutPage_PDFEmbedded_text__ = "Using this tool you can create a PDF file where you can store any other file inside it. You can also store string or code inside it.\n"
__aboutPage_PDFJavascript_title__ = "Create PDF Javascript"
__aboutPage_PDFJavascript_text__ = "Using this tool you can add javascript code or javascript file to create a PDF file using that code as embedded.\n"